server:
  port: 8002
rabbitmq:
  queue: declarationform
spring:
  rabbitmq:
    host: 192.168.1.11
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
