server:
  port: 8013
zuul:
  routes:
    tax:
      serviceId: tax
    taxCutting:
      serviceId: taxCutting
    license:
      serviceId: license
    form:
      serviceId: form
    formUI:
      serviceId: formUI
    manifest:
      serviceId: manifest
    riskAnalysis:
      serviceId: riskAnalysis
    cottonQuota:
      serviceId: cottonQuota
    processingTrade:
      serviceId: processingTrade
    baseData:
      serviceId: baseData
ribbon:
  eureka:
    enabled: false
